rg_name              = "aztf-challenge-02"
location             = "westeurope"
db_name              = "products"
sql_adm_username     = "sqladmin"
mongodb_adm_username = "mongodbadmin"
container_group_name = "aztf-containergroup"
