---
name: Terraform

on:
    push:
        branches:
            - challenge-02

jobs:
    terraform:
        name: Terraform
        runs-on: ubuntu-latest
        env:
            ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
            ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
            ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
            ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v1.1.0
              with:
                  terraform_version: 0.12.23

            - name: Terraform Init
              run: terraform init

            - name: Terraform Validate
              run: terraform validate

            - name: Terraform Format
              run: terraform fmt -check

            - name: Terraform Plan
              run: terraform plan -var "app_service_name=${{ secrets.WEBAPP_APPSERVICE_NAME }}" -var "sql_adm_password=${{ secrets.SQL_ADM_PASSWORD }}"
                  -input=false -out tfplan

            - name: Terraform Apply
              run: terraform apply -auto-approve tfplan
